baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'thoughts'
theme = "hugo-blog-awesome"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[menu]
  [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "/blogs/"
    weight = 1
